Add test calling FeatureNames at varying stack depths
Ethtool.getNames can fail when calling the ETHTOOL_GSSET_INFO ioctl
if the morestack prologue of Ethtool.ioctl grows the stack. This is
because the ssetInfo variable is stored on the stack, and uintptr is
opaque and not updated when the stack is moved.

Add a test `TestFeatureNamesStackDepth` to assert the correctness at varying
stack depths. It is expected to fail at this commit and will be fixed in
the next.

```
--- FAIL: TestFeatureNamesStackDepth (0.00s)
    ethtool_test.go:224: FeatureNames("lo") incorrect at stack depth=10: got 0 features, want 60.
```